spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cache?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 960829
#    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1

#  开启驼峰匹配命名规则
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.james.springbootcache.mapper: debug

# debug: true
